import numpy as np
import torch
from torch_geometric.data import Data
from tqdm import tqdm
import torch


class GraphsEmbedding:
    def __init__(self, edge_type):
        self.edge_type = edge_type.upper()

    def __call__(self, nodes_dict):
        edge_index = [[], []]
        
        mapping = {str(nid): i for i, nid in enumerate(nodes_dict.keys())}
        
        for node_id, node_obj in nodes_dict.items():
            # Use the raw_node we saved in Node.__init__
            node_raw_data = node_obj.raw_node 
            
            for edge in node_raw_data.get('edges', []):
                # Prefer the explicit 'type' field added by the updated Joern script;
                # fall back to parsing the 'id' string for CPG files generated by
                # older versions of the script that lack the 'type' field.
                explicit_type = edge.get('type', '').upper()
                edge_id_full = edge['id'].lower()

                is_match = False
                if self.edge_type == "AST":
                    is_match = (explicit_type == "AST") or (not explicit_type and "ast" in edge_id_full)
                elif self.edge_type == "CFG":
                    is_match = (explicit_type == "CFG") or (not explicit_type and "cfg" in edge_id_full)
                elif self.edge_type == "PDG":
                    if explicit_type:
                        is_match = explicit_type in ("REACHING_DEF", "CDG")
                    else:
                        # Handle both "reaching_def" (with underscore) and "reachingdef"
                        is_match = ("reaching_def" in edge_id_full or
                                    "reachingdef" in edge_id_full or
                                    "cdg" in edge_id_full)
                
                if is_match:
                    s_id = str(edge['out'])
                    t_id = str(edge['in'])
                    
                    if s_id in mapping and t_id in mapping:
                        edge_index[0].append(mapping[s_id])
                        edge_index[1].append(mapping[t_id])
        return edge_index
                    

class NodesEmbedding:
    def __init__(self, nodes_dim, tokenizer, model, device="cpu"):
        self.nodes_dim = nodes_dim
        self.tokenizer = tokenizer
        self.model = model
        self.device = device
        self.kv_size = 768 

    def embed_nodes(self, nodes):
        node_items = list(nodes.items())
        
        # Batch tokenize all node codes at once
        node_codes = [node.get_code() or "empty" for _, node in node_items]
        inputs = self.tokenizer(node_codes, return_tensors="pt", truncation=True, 
                            padding=True, max_length=128).to(self.device)
        
        # Single forward pass for all nodes instead of one per node
        with torch.no_grad():
            outputs = self.model(**inputs)
        
        # Extract CLS token embeddings for all nodes at once
        source_embeddings = outputs.last_hidden_state[:, 0, :]  # (num_nodes, 768)
        
        # Concatenate with node types
        embeddings = []
        for i, (_, node) in enumerate(node_items):
            embedding = np.concatenate((np.array([node.type]), source_embeddings[i].cpu().numpy()), axis=0)
            embeddings.append(embedding)
        
        return torch.from_numpy(np.array(embeddings)).float()

    def __call__(self, nodes):
        target = torch.zeros(self.nodes_dim, self.kv_size + 1).float()
        embedded_nodes = self.embed_nodes(nodes)
        num_nodes = min(embedded_nodes.size(0), self.nodes_dim)
        target[:num_nodes, :] = embedded_nodes[:num_nodes, :]
        return target


def nodes_to_input(nodes, target, nodes_dim, nodes_embed_instance, graphs_embed_instance):
    """
    nodes: The dict {id: Node} from parse_to_nodes
    """
    # Create specific engines for each view
    ast_embed = GraphsEmbedding("Ast")
    cfg_embed = GraphsEmbedding("Cfg")
    pdg_embed = GraphsEmbedding("Pdg")
    
    # Generate the three distinct indices
    edge_ast = ast_embed(nodes)
    edge_cfg = cfg_embed(nodes)
    edge_pdg = pdg_embed(nodes)
    
    label = torch.tensor([target]).float()

    def to_tensor(edge_list):
        if len(edge_list[0]) == 0:
            return torch.empty((2, 0), dtype=torch.long)
        return torch.tensor(edge_list, dtype=torch.long)

    return Data(
        x=nodes_embed_instance(nodes), 
        edge_index_ast=to_tensor(edge_ast),
        edge_index_cfg=to_tensor(edge_cfg),
        edge_index_pdg=to_tensor(edge_pdg),
        y=label
    )