import numpy as np
import torch
import networkx as nx
from torch_geometric.data import Data
from tqdm import tqdm


class GraphsEmbedding:
    def __init__(self, edge_type):
        self.edge_type = edge_type.upper()

    def __call__(self, nodes_dict):
        edge_index = [[], []]
        
        mapping = {str(nid): i for i, nid in enumerate(nodes_dict.keys())}
        
        for node_id, node_obj in nodes_dict.items():
            # Use the raw_node we saved in Node.__init__
            node_raw_data = node_obj.raw_node 
            
            for edge in node_raw_data.get('edges', []):
                # Prefer the explicit 'type' field added by the updated Joern script;
                # fall back to parsing the 'id' string for CPG files generated by
                # older versions of the script that lack the 'type' field.
                explicit_type = edge.get('type', '').upper()
                edge_id_full = edge['id'].lower()

                is_match = False
                if self.edge_type == "AST":
                    is_match = (explicit_type == "AST") or (not explicit_type and "ast" in edge_id_full)
                elif self.edge_type == "CFG":
                    is_match = (explicit_type == "CFG") or (not explicit_type and "cfg" in edge_id_full)
                elif self.edge_type == "PDG":
                    if explicit_type:
                        is_match = explicit_type in ("REACHING_DEF", "CDG")
                    else:
                        # Handle both "reaching_def" (with underscore) and "reachingdef"
                        is_match = ("reaching_def" in edge_id_full or
                                    "reachingdef" in edge_id_full or
                                    "cdg" in edge_id_full)
                
                if is_match:
                    s_id = str(edge['out'])
                    t_id = str(edge['in'])
                    
                    if s_id in mapping and t_id in mapping:
                        edge_index[0].append(mapping[s_id])
                        edge_index[1].append(mapping[t_id])
        return edge_index
                    

class FunctionEmbedding:
    """Embeds the entire function body as a single vector using CodeBERT.

    Rather than encoding each graph node in isolation (which wastes most of the
    128/512-token budget on padding for short nodes), this class encodes the
    *full* function code once at max_length=512, then broadcasts the resulting
    CLS-token representation to every node in the graph.  This ensures that
    every node feature vector carries complete semantic context about the
    surrounding function, which is crucial for identifying vulnerability
    patterns that only manifest at the function level.
    """

    def __init__(self, tokenizer, model, device="cpu"):
        self.tokenizer = tokenizer
        self.model = model
        self.device = device

    def embed(self, func_code: str) -> torch.Tensor:
        """Return the CLS-token embedding for *func_code*.

        Parameters
        ----------
        func_code : str or None
            The full source code of the function to embed.  If ``None`` or an
            empty string is passed, the tokenizer receives the literal string
            ``"empty"`` so that the call is always valid.

        Returns
        -------
        torch.Tensor of shape (768,)
        """
        inputs = self.tokenizer(
            func_code or "empty",
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=512,
        ).to(self.device)

        with torch.no_grad():
            outputs = self.model(**inputs)

        # CLS token → (768,)
        return outputs.last_hidden_state[:, 0, :].squeeze(0)


class NodesEmbedding:
    def __init__(self, tokenizer, model, device="cpu"):
        self.tokenizer = tokenizer
        self.model = model
        self.device = device

    def embed_nodes(self, nodes):
        node_items = list(nodes.items())
        node_codes = []
        for _, node in node_items:
            code = node.get_code()
            if not code:
                # Fallback 1: check parsed properties
                props = node.properties.get() # This returns a proper dict!
                code = props.get('CODE') or props.get('code') or props.get('NAME') or props.get('name')

            if not code:
                # Fallback 2: just use the node label/type
                code = node.label

            node_codes.append(str(code) if code else "empty")

        batch_size = 256
        source_embeddings = []

        with torch.no_grad():
            for i in range(0, len(node_codes), batch_size):
                batch_codes = node_codes[i:i+batch_size]
                inputs = self.tokenizer(batch_codes, return_tensors="pt", truncation=True,
                                    padding=True, max_length=128).to(self.device)
                outputs = self.model(**inputs)
                source_embeddings.append(outputs.last_hidden_state[:, 0, :].cpu().numpy())

        source_embeddings = np.concatenate(source_embeddings, axis=0)  # (num_nodes, 768)

        # One-hot encode node types (70 classes)
        num_node_types = 70
        node_types_indices = np.array([node.type for _, node in node_items], dtype=int)
        node_types_indices = np.clip(node_types_indices, 0, num_node_types - 1)
        node_types_one_hot = np.eye(num_node_types)[node_types_indices].astype(np.float32)
        embeddings = np.concatenate((source_embeddings, node_types_one_hot), axis=1)

        return torch.from_numpy(embeddings).float()

    def __call__(self, nodes):
        # Return variable-length embeddings (no padding!)
        # Shape: (num_actual_nodes, 838)
        return self.embed_nodes(nodes)


def compute_graph_features(edge_ast, edge_cfg, edge_pdg, num_nodes):
    """Compute 6 graph-level structural features that encode vulnerability patterns.

    Features:
        density           – how densely connected the graph is
        avg_degree        – average node connectivity
        cycle_count       – number of directed cycles (capped at 100)
        avg_clustering    – average clustering coefficient
        diameter          – longest shortest path (largest connected component)
        bridge_count      – number of bridge edges (critical connections)

    Parameters
    ----------
    edge_ast, edge_cfg, edge_pdg : list[list[int]]
        Edge lists in the form [[src, ...], [dst, ...]] for each view.
    num_nodes : int
        Total number of nodes in the graph.

    Returns
    -------
    np.ndarray of shape (6,) with dtype float32.
    """
    if num_nodes == 0:
        return np.zeros(6, dtype=np.float32)

    G = nx.Graph()
    G.add_nodes_from(range(num_nodes))
    DG = nx.DiGraph()
    DG.add_nodes_from(range(num_nodes))

    for edge_index in [edge_ast, edge_cfg, edge_pdg]:
        if len(edge_index[0]) > 0:
            edges = list(zip(edge_index[0], edge_index[1]))
            G.add_edges_from(edges)
            DG.add_edges_from(edges)

    if G.number_of_edges() == 0:
        return np.zeros(6, dtype=np.float32)

    density = nx.density(G)
    avg_degree = 2 * G.number_of_edges() / max(G.number_of_nodes(), 1)

    # Cap cycle counting to avoid O(n!) computation on large graphs
    num_cycles = 0
    for _ in nx.simple_cycles(DG):
        num_cycles += 1
        if num_cycles >= 100:
            break

    avg_clustering = nx.average_clustering(G)

    # Diameter of the largest connected component
    if nx.is_connected(G):
        diameter = float(nx.diameter(G))
    else:
        largest_cc = max(nx.connected_components(G), key=len)
        sub = G.subgraph(largest_cc)
        diameter = float(nx.diameter(sub)) if len(largest_cc) > 1 else 0.0

    bridge_count = float(len(list(nx.bridges(G))))

    return np.array([density, avg_degree, num_cycles, avg_clustering, diameter, bridge_count],
                    dtype=np.float32)


def nodes_to_input(nodes, target, node_embed_instance):
    """Build a PyG Data object for a single function graph.

    Parameters
    ----------
    nodes : dict
        The ``{id: Node}`` mapping produced by ``cpg.parse_to_nodes``.
    target : int
        Ground-truth label (1 = vulnerable, 0 = safe).
    node_embed_instance : NodesEmbedding
        Pre-instantiated embedding engine.  Each node's own code snippet is
        encoded individually so that node feature vectors are distinct,
        enabling the GNN to learn control/data flow patterns.

    Returns
    -------
    torch_geometric.data.Data
        Graph with node feature matrix of shape ``(num_nodes, 844)``
        (768 CodeBERT + 70 node-type one-hot + 6 graph features) and three separate
        edge-index tensors for AST / CFG / PDG views.
    """
    num_actual_nodes = len(nodes)

    # Create specific engines for each view
    ast_embed = GraphsEmbedding("Ast")
    cfg_embed = GraphsEmbedding("Cfg")
    pdg_embed = GraphsEmbedding("Pdg")

    # Generate edges on actual nodes (not padded)
    edge_ast = ast_embed(nodes)
    edge_cfg = cfg_embed(nodes)
    edge_pdg = pdg_embed(nodes)

    label = torch.tensor([target]).float()

    def to_tensor(edge_list):
        if len(edge_list[0]) == 0:
            return torch.empty((2, 0), dtype=torch.long)
        return torch.tensor(edge_list, dtype=torch.long)

    # Embed each node's own code snippet individually
    node_features = node_embed_instance(nodes)  # (num_actual_nodes, 838)
    device = node_features.device  # Ensure we use the device CodeBERT outputted on

    # Compute graph features on actual graph structure
    graph_feats = compute_graph_features(edge_ast, edge_cfg, edge_pdg, num_actual_nodes)

    # Broadcast graph features to all nodes
    graph_feats_tensor = torch.tensor(graph_feats, device=device).float().unsqueeze(0).expand(num_actual_nodes, -1)

    # Concatenate: (num_actual_nodes, 844) - VARIABLE LENGTH
    x = torch.cat([node_features, graph_feats_tensor], dim=1)

    # Add batch information for graph pooling
    batch = torch.zeros(num_actual_nodes, dtype=torch.long, device=device)

    return Data(
        x=x,
        edge_index_ast=to_tensor(edge_ast).to(device),
        edge_index_cfg=to_tensor(edge_cfg).to(device),
        edge_index_pdg=to_tensor(edge_pdg).to(device),
        batch=batch,
        y=label.to(device)
    )